# Generated by Django 5.2.8 on 2025-11-29 10:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(help_text='Kategoriyaning nomi (masalan: Elektronika)', max_length=100, unique=True, verbose_name='Kategoriya nomi')),
                ('tavsif', models.TextField(blank=True, help_text="Kategoriya haqida qisqacha ma'lumot", null=True, verbose_name='Tavsif')),
                ('rasm', models.ImageField(blank=True, help_text='Kategoriya uchun rasm yuklang', null=True, upload_to='kategoriyalar/', verbose_name='Rasm')),
                ('faol', models.BooleanField(default=True, help_text='Kategoriya faolmi?', verbose_name='Faol')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('yangilangan_sana', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(help_text="Mahsulotning to'liq nomi", max_length=200, verbose_name='Mahsulot nomi')),
                ('slug', models.SlugField(help_text='URL uchun (masalan: yangi-mahsulot)', max_length=200, unique=True, verbose_name='Slug')),
                ('qisqacha_tavsif', models.CharField(blank=True, help_text="Mahsulot haqida qisqacha ma'lumot", max_length=300, verbose_name='Qisqacha tavsif')),
                ('toliq_tavsif', models.TextField(help_text="Mahsulot haqida batafsil ma'lumot", verbose_name="To'liq tavsif")),
                ('narx', models.DecimalField(decimal_places=2, help_text="Mahsulot narxi (so'mda)", max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narx')),
                ('chegirma_narxi', models.DecimalField(blank=True, decimal_places=2, help_text="Chegirma qo'llanilgan narx", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Chegirma narxi')),
                ('rasm', models.ImageField(help_text='Mahsulot rasmi', upload_to='mahsulotlar/%Y/%m/%d/', verbose_name='Rasm')),
                ('miqdor', models.PositiveIntegerField(default=0, help_text='Omborda mavjud miqdor', verbose_name='Miqdor')),
                ('holat', models.CharField(choices=[('mavjud', 'Mavjud'), ('tugagan', 'Tugagan'), ('buyurtma', 'Buyurtma asosida')], default='mavjud', help_text='Mahsulot holati', max_length=20, verbose_name='Holat')),
                ('mashhur', models.BooleanField(default=False, help_text="Asosiy sahifada ko'rsatilsinmi?", verbose_name='Mashhur')),
                ('yangi', models.BooleanField(default=True, help_text='Yangi mahsulotmi?', verbose_name='Yangi')),
                ('korilganlar_soni', models.PositiveIntegerField(default=0, help_text="Mahsulot necha marta ko'rilgan", verbose_name="Ko'rilganlar soni")),
                ('reyting', models.DecimalField(decimal_places=2, default=0, help_text='Mahsulot reytingi (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Reyting')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('yangilangan_sana', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('kategoriya', models.ForeignKey(help_text='Mahsulot qaysi kategoriyaga tegishli', on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='asosiy_app.kategoriya', verbose_name='Kategoriya')),
                ('yaratuvchi', models.ForeignKey(blank=True, help_text="Mahsulotni kim qo'shgan", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaratgan_mahsulotlar', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-yaratilgan_sana'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='profillar/', verbose_name='Profil rasmi')),
                ('bio', models.TextField(blank=True, help_text="O'zingiz haqingizda qisqacha", max_length=500, verbose_name='Bio')),
                ('tugilgan_sana', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('jins', models.CharField(blank=True, choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10, verbose_name='Jins')),
                ('telefon', models.CharField(blank=True, help_text='+998 90 123 45 67', max_length=20, verbose_name='Telefon raqami')),
                ('manzil', models.TextField(blank=True, verbose_name='Manzil')),
                ('shahar', models.CharField(blank=True, max_length=100, verbose_name='Shahar')),
                ('mamlakat', models.CharField(default="O'zbekiston", max_length=100, verbose_name='Mamlakat')),
                ('vebsayt', models.URLField(blank=True, help_text='https://example.com', verbose_name='Veb-sayt')),
                ('email_xabarnoma', models.BooleanField(default=True, help_text='Email orqali xabarnomalar olishni xohlaysizmi?', verbose_name='Email xabarnomalar')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('yangilangan_sana', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('foydalanuvchi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillar',
            },
        ),
        migrations.CreateModel(
            name='Sharh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField(help_text='Mahsulot haqida fikringiz', verbose_name='Sharh')),
                ('baho', models.PositiveSmallIntegerField(help_text='1 dan 5 gacha baho bering', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Baho')),
                ('tasdiqlangan', models.BooleanField(default=False, help_text='Sharh tasdiqlanganmi?', verbose_name='Tasdiqlanganmi')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharhlar', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharhlar', to='asosiy_app.mahsulot', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-yaratilgan_sana'],
            },
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['slug'], name='asosiy_app__slug_f2933d_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['-yaratilgan_sana'], name='asosiy_app__yaratil_36faa5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sharh',
            unique_together={('mahsulot', 'foydalanuvchi')},
        ),
    ]
